//users and user
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';
export const FETCH_USERS_FULFILLED = 'FETCH_USERS_FULFILLED';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const RESET_ATTENTION_USERS = 'RESET_ATTENTION_USERS';
export const SET_PAGINATION_USERS = 'SET_PAGINATION_USERS';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';
export const GHANGE_USER = "GHANGE_USER";
export const RESET_ATTENTION_USER = 'RESET_ATTENTION_USER';

//posts and post
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED';
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const RESET_ATTENTION_POSTS = 'RESET_ATTENTION_POSTS';
export const SET_PAGINATION_POSTS = 'SET_PAGINATION_POSTS';

export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_REJECTED = 'FETCH_POST_REJECTED';
export const FETCH_POST_FULFILLED = 'FETCH_POST_FULFILLED';
export const GHANGE_POST = "GHANGE_POST";
export const RESET_ATTENTION_POST = 'RESET_ATTENTION_POST';

//comments and comment
export const FETCH_COMMENTS = 'FETCH_COMMENT';
export const FETCH_COMMENTS_REJECTED = 'FETCH_COMMENTS_REJECTED';
export const FETCH_COMMENTS_FULFILLED = 'FETCH_COMMENTS_FULFILLED';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const RESET_ATTENTION_COMMENTS = 'RESET_ATTENTION_COMMENTS';
export const SET_PAGINATION_COMMENTS = 'SET_PAGINATION_COMMENTS';

export const FETCH_COMMENT = 'FETCH_COMMENT';
export const FETCH_COMMENT_REJECTED = 'FETCH_COMMENT_REJECTED';
export const FETCH_COMMENT_FULFILLED = 'FETCH_COMMENT_FULFILLED';
export const GHANGE_COMMENT = "GHANGE_COMMENT";
export const RESET_ATTENTION_COMMENT = 'RESET_ATTENTION_COMMENT';