export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';
export const FETCH_USERS_FULFILLED = 'FETCH_USERS_FULFILLED';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const RESET_ATTENTION_USERS = 'RESET_ATTENTION_USERS';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';
export const GHANGE_USER = "GHANGE_USER";
export const RESET_ATTENTION_USER = 'RESET_ATTENTION_USER';

export const SET_PAGINATION = 'SET_PAGINATION';